[package]
name = "translitrs"
version = "0.2.0"
edition = "2021"
authors = ["Filip Parag <filip@parag.rs>"]
license = "MIT"
description = "Transliteration utility for Serbian language"

[dependencies]
subslice = ">=0.2.3"
regex = ">=1.5.4"
lazy_static = ">=1.4.0"
pandoc_ast = ">=0.8.0"
