binop_separator = "Back"
color = "Always"
comment_width = 70
chain_width = 60
edition = "2018"
fn_call_width = 80
imports_layout = "HorizontalVertical"
match_arm_blocks = false
max_width = 100
imports_granularity = "Module"
newline_style = "Unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_lit_single_line = false
tab_spaces = 4
trailing_comma = "Never"
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
